package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,BOOLean,If,
    Then,Else,While,Void,Function,
    Return,Identifier,INTeger,Float,LeftBrace,
    RightBrace,LeftParen,RightParen,Comma,Assign,
    Equal,NotEqual,Less,Greater,GreaterEqual,
    LessEqual,Plus,Minus,Or,And,
    Multiply,Divide,Comment,Not
}
